DROP TABLE IF EXISTS reviews CASCADE;

CREATE TABLE reviews (
  id SERIAL PRIMARY KEY NOT NULL,
  rating NUMERIC NOT NULL,
  description TEXT,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  coffee_id INTEGER REFERENCES coffees(id) ON DELETE CASCADE,
  created_at DATE
);