INSERT INTO reviews (rating, description, user_id, coffee_id)
VALUES
(4, 'Fantastic coffee highly recommended to anyone who loves to drink coffee throughout the day', 1, 1),
(4, 'Love it!', 1, 2),
(4, 'Really surprised how this coffee turned out. Would purchase this item again.', 1, 3),
(5, 'Really like this coffee, smooth and elegant!', 3, 2),
(5, 'Amazing coffee, really great for the mornings',3, 3),
(2, 'Didnt like this one so much...', 3, 5),
(3, 'Great coffee :)', 3, 4),
(1, 'Actually kicked my ass, do not recommend', 2, 3),
(3, 'Just enough ass kicking!!', 2, 4),
(1, 'Save your money and buy real beans', 2, 5),
(2, 'Had higher expectations', 2, 6),
(4, 'Really surprised how this coffee turned out. Would purchase this item again.', 1, 23),
(5, 'Really surprised how this coffee turned out.', 2, 23),
